name: nce-plrec
dependencies:
  - python=2.7.10
  - cython=0.28.5
  - scipy=1.0.0
  - numpy=1.14.1
  - scikit-learn=0.19.0
  - pandas=0.20.3
  - tqdm=4.11.2
  - argparse=1.1
  - tensorflow_gpu=1.4.0
  - matplotlib=3.0.0
  - pyyaml=4.1
  - fbpca=1.0

