parameters:
    models: IFVAE
    similarity: Cosine
    corruption: [0]
    alpha: [0]
    rank: [50, 100, 200]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    iter: 300
    lambda: [0.00001, 0.0001]
    metric: [R-Precision, NDCG, Precision, Recall]