parameters:
    models: NCE-PLRec
    similarity: Cosine
    corruption: [0]
    alpha: [1]
    rank: [50, 100, 200]
    root: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]
    topK: [5, 10, 15, 20, 50]
    iter: 10
    lambda: [1, 10, 100, 1000, 10000]
    metric: [R-Precision, NDCG, Precision, Recall]