parameters:
    models: POP
    similarity: Cosine
    corruption: [0]
    alpha: [1]
    rank: [1]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    iter: 1
    lambda: [1]
    metric: [R-Precision, NDCG, Precision, Recall]