parameters:
    models: WRMF
    similarity: Cosine
    corruption: [0]
    alpha: [10000]
    rank: [100]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    iter: 10
    lambda: [1, 10, 100, 1000, 10000]
    metric: [R-Precision, NDCG, Precision, Recall]